[build]
    command = "npm run build"
    publish = "build/"

[context.deploy-preview]
VITE_CONTENTFUL_DELIVERY_API_ACCESS_TOKEN = "$VITE_CONTENTFUL_PREVIEW_API_ACCESS_TOKEN"
VITE_CONTENTFUL_PREVIEW = "enabled"