[build]
    command = "npm run build"
    publish = "build/"

[context.deploy-preview]
    command = "VITE_CONTENTFUL_DELIVERY_API_ACCESS_TOKEN=$VITE_CONTENTFUL_PREVIEW_API_ACCESS_TOKEN npm run build"

[context.deploy-preview.environment]
    VITE_CONTENTFUL_PREVIEW = "enabled"

[context.staging]
    command = "VITE_CONTENTFUL_DELIVERY_API_ACCESS_TOKEN=$VITE_CONTENTFUL_PREVIEW_API_ACCESS_TOKEN npm run build"

[context.staging.environment]
    VITE_CONTENTFUL_PREVIEW = "enabled"